package main

var keyboardMap = map[string][]string{ // this was a PAIN to make
	"a":  {"s", "z", "q"},
	"b":  {"v", "g", "h", "n"},
	"c":  {"v", "x", "d", "f"},
	"d":  {"f", "e", "s"},
	"e":  {"w", "s", "d", "r"},
	"f":  {"d", "r", "g"},
	"g":  {"f", "t", "h"},
	"h":  {"g", "y", "j"},
	"i":  {"u", "o", "k"},
	"j":  {"h", "u", "k"},
	"k":  {"j", "i", "l", "m"},
	"l":  {"k", "o", "p"},
	"m":  {"n", "j", "k", ","},
	"n":  {"b", "h", "j", "m"},
	"o":  {"i", "p", "l", "0"},
	"p":  {"o", "l", "["},
	"q":  {"w", "a", "1"},
	"r":  {"e", "t", "f"},
	"s":  {"a", "w", "e", "d", "z", "x"},
	"t":  {"r", "y", "g"},
	"u":  {"y", "i", "j"},
	"v":  {"c", "f", "g", "b"},
	"w":  {"q", "a", "s", "e"},
	"x":  {"z", "s", "d", "c"},
	"y":  {"t", "u", "h"},
	"z":  {"a", "s", "x"},
	"1":  {"2", "q", "`"},
	"2":  {"1", "3", "w", "q"},
	"3":  {"2", "4", "e", "w"},
	"4":  {"3", "5", "r", "e"},
	"5":  {"4", "6", "t", "r"},
	"6":  {"5", "7", "y", "t"},
	"7":  {"6", "8", "u", "y"},
	"8":  {"7", "9", "i", "u"},
	"9":  {"8", "0", "o", "i"},
	"0":  {"9", "-", "p", "o"},
	"-":  {"0", "=", "p", "["},
	"=":  {"-", "[", "]", "\\"},
	"`":  {"1", "t", "\\"},
	"[":  {"=", "]", "\\", ";", "'"},
	"]":  {"[", "\\", "p", ";", "'"},
	"\\": {"]", "["},
	";":  {"'", "l", "k", "."},
	"'":  {";", "/", "l", "k", "[", "]", "\\"},
	",":  {"m", ".", "/"},
	".":  {",", "/", ";"},
	"/":  {".", ",", "'", "'"},
	" ":  {" "}, // this will never be used because it cannot be replaced :)
}

var wordReplacements = map[string][]string{
	// A for AUGH
	"absence":      {"absense", "abscence"},
	"acceptable":   {"acceptible", "exceptable"},
	"accidentally": {"accidently", "accidentaly"},
	"accommodate":  {"accomodate", "acommodate"},
	"achieve":      {"acheive", "achiev"},
	"acknowledge":  {"acknowledgement", "acknowlege"},
	"acquire":      {"aquire", "accquire"},
	"across":       {"accross", "acrost"},
	"address":      {"adress", "addres"},
	"affect":       {"effect"},
	"aggressive":   {"agressive", "agresive"},
	"agree":        {"aggree", "agre"},
	"all right":    {"alright"},
	"a lot":        {"alot"},
	"amateur":      {"amatuer", "amature"},
	"among":        {"amoung", "amung"},
	"apparent":     {"aparent", "apparant"},
	"appearance":   {"appearence", "appearrance"},
	"argument":     {"arguement"},
	"arctic":       {"artic"},
	"assist":       {"asist", "assit"},
	"asthma":       {"asma", "asthama"},
	"athlete":      {"athelete", "athleat"},
	"attendance":   {"attendence", "attendense"},
	"audience":     {"audince", "audiance"},

	// B for brain tired
	"balance":   {"ballance", "balence"},
	"basically": {"basicly", "bassically"},
	"because":   {"becuase", "beacuse"},
	"before":    {"befor", "bfore"},
	"beginning": {"begining", "beggining"},
	"believe":   {"beleive", "belive"},
	"benefit":   {"benifit", "beniffit"},
	"between":   {"betwen", "beetween"},
	"bicycle":   {"bycicle", "bycycle"},
	"biscuit":   {"biscut", "biskit"},
	"business":  {"buisness", "bussiness"},

	// C for can't do this anymore
	"calendar":    {"calender", "calander"},
	"campaign":    {"campain"},
	"can't":       {"cant"},
	"caribbean":   {"carribean"},
	"category":    {"catagory", "catagorie"},
	"cemetery":    {"cemetary", "cematery"},
	"challenge":   {"chalange"},
	"change":      {"chang"},
	"choose":      {"chose"},
	"clothes":     {"cloths", "close"},
	"coming":      {"comming", "comeing"},
	"commit":      {"comitt", "comit"},
	"committee":   {"comittee", "commitee"},
	"completely":  {"completly", "completley"},
	"conscious":   {"concious", "conscous"},
	"convenience": {"conveniance", "convenince"},
	"coolly":      {"cooly"},
	"could've":    {"could of"},
	"country":     {"counrty", "countrey"},
	"course":      {"corse"},

	// D for dying
	"definitely": {"definately", "definitly"},
	"dependent":  {"dependant", "depentant"},
	"describe":   {"discribe", "decribe"},
	"desperate":  {"desparate", "desperat"},
	"develop":    {"develope", "devlope"},
	"difference": {"differance", "differrence"},
	"difficult":  {"dificult", "difficault"},
	"disappoint": {"disapoint", "dissapoint"},
	"discipline": {"disipline", "disiplin"},
	"doesn't":    {"doesnt"},
	"during":     {"durring"},

	// E easy because this section isn't too long
	"easy":        {"eazy"},
	"effect":      {"affect"},
	"eighth":      {"eigth"},

}
